version: '3.7'

services:

    postgres-database:
        image: postgres:11.2
        container_name: standalone_postgres
        working_dir: /docker-entrypoint-initdb.d
        environment:
            POSTGRES_DB: forest_postgres
            POSTGRES_USER: forest
            POSTGRES_PASSWORD: secret
        ports:
            - 5417:5432
        volumes:
            - .:/docker-entrypoint-initdb.d
